pipeline {
	agent none
	stages {
		stage("build & SonarQube analysis") {
			agent any
			steps {
				withSonarQubeEnv('sonarqube-8.6.1.40680') {
					sh 'mvn sonar:sonar'
				}
			}
		}
		stage("Quality Gate") {
			steps {
				timeout(time: 1, unit: 'HOURS') {
					waitForQualityGate abortPipeline: true
				}
			}
		}
	}
}